### ISSUE TITLE
SDS Actions Menu - Disabled Action Styling

### ISSUE THREAD

**Issue by brandydanner-gsa** [GSA/sam-design-system#1305]
**Components Involved**
sds-actions-menu

**Expected Behavior**
When an action's mode is set to disabled the styling should be correct.

**Actual Behavior**
When an action's mode is set to disabled there is a gray border that the other menu items don't have.

**Your Environment**
Angular Version: 14.3.0
@gsa-sam packages version:
"@gsa-sam/components": "14.0.3",
"@gsa-sam/layout": "14.0.13",
"@gsa-sam/layouts": "14.0.3",
"@gsa-sam/ngx-uswds": "14.0.2",
"@gsa-sam/ngx-uswds-icons": "14.0.0-beta.2",
"@gsa-sam/sam-formly": "14.0.3",
"@gsa-sam/sam-material-extensions": "14.0.3",
"@gsa-sam/sam-styles": "3.0.8",
"@gsa-sam/shared": "14.0.13",

**Ticket Number**
IAEMOD-17295

**Additional context**

I believe this happened after the USWDS upgrade.  See the Action Menu item "Update" which is a disabled action menu item via the action menu config.  It shouldn't have the gray border.
<img width="1114" alt="image" src="https://github.com/GSA/sam-design-system/assets/75684861/776519f1-ae45-49ee-8ba6-5f53c6a76f70">

Code is similar to: https://github.com/GSA/sam-design-system/blob/master/libs/documentation/src/lib/components/actions/demos/action-mode/actions-action-mode.component.ts#L39

**Comment by yerramshilpa** [comment]
Issue resolved in the below versions

[@gsa-sam/sam-styles](https://www.npmjs.com/package/@gsa-sam/sam-styles) 3.0.11
[@gsa-sam/components](https://www.npmjs.com/package/@gsa-sam/components) 15.0.1

**Comment by brandydanner-gsa** [comment]
@yerramshilpa I am still seeing this issue:

<img width="1022" alt="image" src="https://github.com/GSA/sam-design-system/assets/75684861/941dc1e6-fbea-41d1-ba22-a94f292ed716">

Updated packages:
<img width="371" alt="image" src="https://github.com/GSA/sam-design-system/assets/75684861/b7c1758f-2c42-4c76-99be-a8b6c4ff19b9">

**Comment by brandydanner-gsa** [comment]
@yerramshilpa 

Here are the styles that are being applied if it helps:
<img width="1432" alt="image" src="https://github.com/GSA/sam-design-system/assets/75684861/b0e8be02-599f-49d4-a503-63533ccb8cb6">
