### ISSUE TITLE
History: Multiple API calls when enabling history, and sanitizing HTML warning 

### ISSUE THREAD

**Issue by KidanyGSA** [GSA/sam-design-system#357]
With history disabled we get one API call on load as intended and we actually see that now the getData() is being called once when the filterModel has values. But when the history is enabled we are getting 3 API calls on load.
![image](https://user-images.githubusercontent.com/66032295/93249586-898e9c80-f75f-11ea-9734-9ab2e55c3478.png)

**Comment by yerramshilpa** [comment]
The issue is resolved in the @gsa-sam/sam-formly@0.6.26 version.

**Comment by KidanyGSA** [comment]
@yerramshilpa I'm still seeing the issue. Regular booked marked url with a keyword search is executing 4 api calls on load. Also I still see the sanitizing warning.
![image](https://user-images.githubusercontent.com/66032295/94939492-3b3c0600-04a0-11eb-9e9e-50b3feeb661f.png)
