### ISSUE TITLE
Small circle button icon alignment

### ISSUE THREAD

**Issue by davereed** [GSA/sam-design-system#768]
**Components Involved**
usa-icon / sds-icon

**Expected Behavior**
Icon should be centered

**Actual Behavior**
Icon is offset to the top and left of the button

**Your Environment**
Latests SDS / Sam-Styles / Icon Lib

**Ticket Number**
TBD, will have to get it from Cotton Candy.

**Additional context**
Icon looks centered on sam-styles, so is likely related to the upgrade to the new icon packages.

**Comment by cwolf10** [comment]
Stacked icon alignment fixed with version 11.0.2

**Comment by rtencic-gsa** [comment]
@cwolf10 issue still appears. Main difference notices from implementation on SDS which seems to be fine is we are using usa-icon and not i 

![image](https://user-images.githubusercontent.com/79877133/141006142-c5402cb6-11ce-4e26-8735-4f590541b90a.png)
