### ISSUE TITLE
ngx-uswds SideNavigation component: expandType = 'single' with grandchildren and great-grandchildren

### ISSUE THREAD

**Issue by addiedavis** [GSA/sam-design-system#919]
I believe this is a feature request since this component appears to have been made with only parent/child relationships and not with larger nested trees

When selecting a grandchild or great grandchild using the ngx-uswds SideNavigation component it will collapse up to the child.
How to recreate:
1. Use the ngx-uswds SideNavigation component
2. sideNavContent must have more than two levels (i.e. parent, child, grandchild)
3. expandType='single'
4. open component and select a grandchild or great grandchild 

**Describe the desired solution**
Ideally, the component with expandType = 'single' will persist all parental layers related to the selected grandchild and collapse all non-relative layers

**Describe alternatives you've considered**
currently we are using expandType = 'multiple' to persist the layers, however the trees are rather large and this makes for a lesser user experience 

**Additional context**
Before and after selecting "Using Saved Searches" when expandType = 'single'. This is the child under "Searching for Information in SAM.gov"; "Searching for Information in SAM.gov" is the child under "Help for Non-Federal Users"

![image](https://user-images.githubusercontent.com/32769685/155165069-4f099711-df1d-4bf3-b65b-85524ebd9424.png)
![image](https://user-images.githubusercontent.com/32769685/155165180-90717a6a-bda1-4b52-aba4-81c23d7001cf.png)

**Comment by cwolf10** [comment]
@addiedavis This issue is resolved in v11.0.0 of ngx-uswds.

**Comment by addiedavis** [comment]
@cwolf10 Hi - looking at v11.0.0 under https://gsa.github.io/ngx-uswds/?path=/story/components-sidenavigation--basic I am still seeing grandchildren collapse when selected. 

when expandType='single' 
autoCollapseLabels is either true or false 

When I open Accordion, then Accordion-Child, then select Accordion-Grandchild the Accordion-Grandchild still disappears.

**Comment by cwolf10** [comment]
Hey Addie, can you try clearing your cache and check again? I just checked and it seems to be working as expected
<img width="636" alt="Screen Shot 2022-03-25 at 1 01 14 PM" src="https://user-images.githubusercontent.com/72805180/160167380-861867bc-7540-463c-b63d-e6698e4c90fb.png">
.

**Comment by addiedavis** [comment]
@cwolf10 Thank you! It's looking really good.

One quick question. Are the updates for this going to be added to the Angular 12 libs?

**Comment by cwolf10** [comment]
Glad it's appearing correctly for you now! Yes, this will be pulled into the v12 release, I believe on Monday.
